/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Aluno' at '17/08/16 19:36' with Gradle 2.9
 *
 * @author Aluno, @date 17/08/16 19:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
